# Week 3 - Codes File

In [42]:
# Week 3: NumPy & Pandas Programming
import numpy as np
import pandas as pd
print("=== Week 3: NumPy & Pandas Programming ===")
print("Topics: NumPy Arrays, Pandas DataFrames, Data Manipulation")

=== Week 3: NumPy & Pandas Programming ===
Topics: NumPy Arrays, Pandas DataFrames, Data Manipulation


### Task 28 – Creating Arrays

In [43]:
# Creating arrays from Python lists
list_data = [1, 2, 3, 4, 5]
arr_from_list = np.array(list_data)
print("Array from list:", arr_from_list)

# Creating arrays using built-in methods
zeros_arr = np.zeros((3, 3))       # 3x3 array of zeros
ones_arr = np.ones((2, 4))         # 2x4 array of ones
range_arr = np.arange(0, 10, 2)    # numbers from 0 to 10 step 2
linspace_arr = np.linspace(0, 1, 5) # 5 values from 0 to 1 equally spaced

print("Zeros:\n", zeros_arr)
print("Ones:\n", ones_arr)
print("Range:", range_arr)
print("Linspace:", linspace_arr)

# Random arrays
rand_arr = np.random.rand(3, 3)              # random values between 0 and 1
randint_arr = np.random.randint(1, 10, size=(3, 3)) # random integers
print("Random (0-1):\n", rand_arr)
print("Random Integers:\n", randint_arr)


Array from list: [1 2 3 4 5]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Random (0-1):
 [[0.64347611 0.26956629 0.72015944]
 [0.98955757 0.25942206 0.94170809]
 [0.10834269 0.9804029  0.22333052]]
Random Integers:
 [[3 3 6]
 [4 8 4]
 [2 6 9]]


### Task 29 – Indexing Arrays

In [44]:
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)

# Accessing elements
print("First element:", arr[0])
print("Last element:", arr[-1])

# 2D Array indexing
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("2D Array:\n", arr2d)
print("Element at row 1, col 2:", arr2d[0, 1])   # value 2
print("Element at last row, last col:", arr2d[-1, -1])  # value 9


Original array: [10 20 30 40 50]
First element: 10
Last element: 50
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 2
Element at last row, last col: 9


### Task 30 – Slicing Arrays

In [45]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print("Original:", arr)

# Slicing
print("arr[1:5]:", arr[1:5])   # elements from index 1 to 4
print("arr[:4]:", arr[:4])     # first 4 elements
print("arr[3:]:", arr[3:])     # elements from index 3 onwards
print("arr[::2]:", arr[::2])   # every second element

# 2D slicing
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print("2D Array:\n", arr2d)
print("First 2 rows & 3 cols:\n", arr2d[:2, :3])
print("Last 2 rows:\n", arr2d[-2:, :])


Original: [10 20 30 40 50 60 70]
arr[1:5]: [20 30 40 50]
arr[:4]: [10 20 30 40]
arr[3:]: [40 50 60 70]
arr[::2]: [10 30 50 70]
2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First 2 rows & 3 cols:
 [[1 2 3]
 [5 6 7]]
Last 2 rows:
 [[ 5  6  7  8]
 [ 9 10 11 12]]


### Task 31 – Data Types

In [46]:
arr = np.array([1, 2, 3, 4])
print("Default dtype:", arr.dtype)

# Specifying dtype
arr_float = np.array([1, 2, 3], dtype='float32')
print("Float array:", arr_float)

# Type casting
arr_cast = arr_float.astype('int')
print("Casted to int:", arr_cast)


Default dtype: int64
Float array: [1. 2. 3.]
Casted to int: [1 2 3]


### Task 32 – Copying and Views

In [47]:
arr = np.array([1, 2, 3, 4, 5])

# Copy
arr_copy = arr.copy()
arr_copy[0] = 100
print("Original:", arr)
print("Copy (changed):", arr_copy)

# View
arr_view = arr.view()
arr_view[1] = 200
print("Original (after view change):", arr)
print("View:", arr_view)


Original: [1 2 3 4 5]
Copy (changed): [100   2   3   4   5]
Original (after view change): [  1 200   3   4   5]
View: [  1 200   3   4   5]


### Task 33 – Array Shape

In [48]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)   # rows, cols
print("Dimensions:", arr.ndim)
print("Size:", arr.size)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6


### Task 34 – Reshaping Arrays

In [49]:
arr = np.arange(1, 13)  # 1 to 12
print("Original array:", arr)

reshaped = arr.reshape(3, 4)   # reshape into 3x4
print("Reshaped 3x4:\n", reshaped)

flattened = reshaped.flatten() # 1D version
print("Flattened:", flattened)


Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]


### Task 35 – Iterating Arrays

In [50]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Row-wise iteration:")
for row in arr:
    print(row)

print("Element-wise iteration:")
for x in np.nditer(arr):
    print(x, end=" ")


Row-wise iteration:
[1 2 3]
[4 5 6]
Element-wise iteration:
1 2 3 4 5 6 

### Task 36 – Joining Arrays

In [51]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate
concat = np.concatenate((arr1, arr2))
print("Concatenated:", concat)

# Stack
vstacked = np.vstack((arr1, arr2))   # vertical
hstacked = np.hstack((arr1, arr2))   # horizontal

print("Vertical Stack:\n", vstacked)
print("Horizontal Stack:", hstacked)


Concatenated: [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack: [1 2 3 4 5 6]


### Task 37 – Splitting Arrays

In [52]:
arr = np.array([10, 20, 30, 40, 50, 60])

split_arr = np.split(arr, 3)   # split into 3 parts
print("Split into 3 arrays:", split_arr)

arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

hsplit_arr = np.hsplit(arr2d, 2)  # split into 2 by columns
vsplit_arr = np.vsplit(arr2d, 2)  # split into 2 by rows

print("Horizontal Split:", hsplit_arr)
print("Vertical Split:", vsplit_arr)


Split into 3 arrays: [array([10, 20]), array([30, 40]), array([50, 60])]
Horizontal Split: [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
Vertical Split: [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


### Task 38 – Searching Arrays

In [53]:
arr = np.array([10, 20, 30, 40, 50, 20])

# Find index of first occurrence
idx = np.where(arr == 20)
print("Indices of 20:", idx)

# Condition search
greater_than_30 = np.where(arr > 30)
print("Indices where value > 30:", greater_than_30)


Indices of 20: (array([1, 5]),)
Indices where value > 30: (array([3, 4]),)


### Task 39 – Sorting Arrays

In [54]:
arr = np.array([50, 10, 40, 20, 30])
print("Original:", arr)

sorted_arr = np.sort(arr)
print("Sorted:", sorted_arr)

arr2d = np.array([[3, 2, 1],
                  [6, 5, 4]])
print("2D Sorted (row-wise):\n", np.sort(arr2d))


Original: [50 10 40 20 30]
Sorted: [10 20 30 40 50]
2D Sorted (row-wise):
 [[1 2 3]
 [4 5 6]]


### Task 40 – Random Numbers

In [55]:
# Random floats between 0 and 1
rand_floats = np.random.rand(5)
print("Random floats:", rand_floats)

# Random integers
rand_ints = np.random.randint(1, 100, size=5)
print("Random integers:", rand_ints)

# Random choice from list
choices = np.random.choice([1, 3, 5, 7, 9], size=5)
print("Random choice:", choices)

# Shuffle an array
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("Shuffled array:", arr)


Random floats: [0.36801408 0.46839833 0.87809328 0.51912729 0.13256091]
Random integers: [95  1 69 77 73]
Random choice: [1 7 5 3 1]
Shuffled array: [4 3 1 2 5]


## Task 41 – Pandas Basics

In [56]:
# Creating a simple Series
data = [10, 20, 30, 40]
s = pd.Series(data)
print("Series:\n", s)

# Creating a simple DataFrame
df = pd.DataFrame({
    "Name": ["Ali", "Sara", "John"],
    "Age": [22, 25, 28],
    "Score": [85, 90, 95]
})
print("\nDataFrame:\n", df)


Series:
 0    10
1    20
2    30
3    40
dtype: int64

DataFrame:
    Name  Age  Score
0   Ali   22     85
1  Sara   25     90
2  John   28     95


### Task 42 – Pandas Installation

In [57]:
# Checking Pandas version
print("Pandas version:", pd.__version__)


Pandas version: 2.2.3


### Task 43 – Pandas Series

In [58]:
# Creating a Series with custom index
s = pd.Series([100, 200, 300], index=["a", "b", "c"])
print("Series with custom index:\n", s)

# Accessing elements
print("Element at index 'b':", s["b"])


Series with custom index:
 a    100
b    200
c    300
dtype: int64
Element at index 'b': 200


### Task 44 – Pandas DataFrame

In [59]:
# Creating a DataFrame from dictionary
data = {
    "Product": ["Laptop", "Phone", "Tablet"],
    "Price": [80000, 40000, 30000],
    "Stock": [10, 50, 30]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

# Accessing columns
print("\nPrice column:\n", df["Price"])


DataFrame:
   Product  Price  Stock
0  Laptop  80000     10
1   Phone  40000     50
2  Tablet  30000     30

Price column:
 0    80000
1    40000
2    30000
Name: Price, dtype: int64


### Task 45 – Opening CSV Files

In [60]:
# Reading a CSV file (assuming 'data.csv' exists in working directory)
# df = pd.read_csv("data.csv")
# print(df.head())

# For demonstration, creating CSV from DataFrame
df.to_csv("products.csv", index=False)
loaded_df = pd.read_csv("products.csv")
print("CSV loaded DataFrame:\n", loaded_df)


CSV loaded DataFrame:
   Product  Price  Stock
0  Laptop  80000     10
1   Phone  40000     50
2  Tablet  30000     30


### Task 46 – Data Analysis

In [61]:
# Sample DataFrame
data = {
    "Name": ["Ali", "Sara", "John", "Maria"],
    "Age": [22, 25, 28, 30],
    "Score": [85, 90, 95, 80]
}
df = pd.DataFrame(data)

print("Head:\n", df.head(2))
print("\nInfo:\n")
print(df.info())
print("\nDescribe:\n", df.describe())


Head:
    Name  Age  Score
0   Ali   22     85
1  Sara   25     90

Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   Score   4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes
None

Describe:
          Age      Score
count   4.00   4.000000
mean   26.25  87.500000
std     3.50   6.454972
min    22.00  80.000000
25%    24.25  83.750000
50%    26.50  87.500000
75%    28.50  91.250000
max    30.00  95.000000


### Task 47 – Data Cleaning

In [62]:
# DataFrame with missing values
data = {
    "Name": ["Ali", "Sara", "John", None],
    "Age": [22, None, 28, 30],
    "Score": [85, 90, None, 80]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Dropping missing values
print("\nDrop missing values:\n", df.dropna())

# Filling missing values
print("\nFill missing values:\n", df.fillna({"Name": "Unknown", "Age": 0, "Score": 0}))


Original DataFrame:
    Name   Age  Score
0   Ali  22.0   85.0
1  Sara   NaN   90.0
2  John  28.0    NaN
3  None  30.0   80.0

Drop missing values:
   Name   Age  Score
0  Ali  22.0   85.0

Fill missing values:
       Name   Age  Score
0      Ali  22.0   85.0
1     Sara   0.0   90.0
2     John  28.0    0.0
3  Unknown  30.0   80.0


### Task 48 – Data Correlation

In [63]:
# Sample numeric DataFrame
data = {
    "Math": [90, 85, 78, 92, 88],
    "Science": [80, 88, 84, 90, 86],
    "English": [70, 75, 80, 85, 90]
}
df = pd.DataFrame(data)

# Correlation matrix
print("Correlation matrix:\n", df.corr())


Correlation matrix:
              Math   Science   English
Math     1.000000  0.180944  0.086893
Science  0.180944  1.000000  0.575396
English  0.086893  0.575396  1.000000
